### ISSUE TITLE
Demonstrate how to skip the check in GHA, in README

### ISSUE THREAD

**Issue by webknjaz** [platisd/bad-commit-message-blocker#10]
I've faced a need to skip checking the commits created by Dependabot (because I cannot control them). I think it'd be useful to include the solution in that snippet in README. It could be `if: github.event.pull_request.user.login != 'dependabot[bot]'` based on https://api.github.com/users/dependabot%5Bbot%5D.

A more generic solution would be to ignore any commits created by GitHub Apps: `if: github.event.pull_request.user.type != 'Bot'`.

**Comment by platisd** [comment]
Cool idea. Feel free to do the honors by creating a pull request, otherwise I will try to do this myself in the next days or so.
